# Generated by Django 3.1.7 on 2021-03-09 17:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
